USE [master]
GO
--Validación si la DB existe
IF(db_id('DBVENTAS')IS NOT NULL)
--si existe la elimina
 DROP DATABASE DBVENTAS
--Creación de DB
CREATE DATABASE [DBVENTAS]
GO
USE [DBVENTAS] 
GO

/*===============================CREACION DE TABLAS==========================================*/
--Tabla categoría
CREATE TABLE [dbo].[Categoria](
	ID_CATEGORIA integer PRIMARY KEY IDENTITY,
	DESCRIPCION varchar(50) NOT NULL UNIQUE,	
	ESTADO_CATEGORIA bit,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO

--Tabla marca
CREATE TABLE [dbo].[Marca](
	ID_MARCA int PRIMARY KEY IDENTITY,
	DESCRIPCION varchar(50) NOT NULL UNIQUE,
	ESTADO_MARCA bit,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO
--Tabla artículo
CREATE TABLE [dbo].[Producto](
	ID_PRODUCTO integer PRIMARY KEY IDENTITY,
	FK_ID_CATEGORIA integer NOT NULL,
	FK_ID_MARCA integer NOT NULL,
	CODIGO varchar(50) NOT NULL,
	DESCRIPCION varchar(100) NOT NULL unique,
	PRECIO_UNIT decimal(11,2) NOT NULL,
	STOCK integer NOT NULL,
	ESTADO_PRODUCTO bit,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
	FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES Categoria(ID_CATEGORIA),
	FOREIGN KEY (FK_ID_MARCA) REFERENCES Marca (ID_MARCA)
);
GO

--Tabla cliente
CREATE TABLE [dbo].[Cliente](
	ID_CLIENTE integer PRIMARY KEY IDENTITY(1,1),
	CODIGO AS ('CL' + RIGHT('0000' + CONVERT(VARCHAR, ID_CLIENTE),(4))),
   NOMBRE varchar(100) NOT NULL,	
   APE_PATERNO varchar(100) NOT NULL,
	APE_MATERNO varchar(100) NOT NULL,
	DNI varchar(8) NOT NULL,
	GENERO char(1) check(GENERO IN('M','F')) NOT NULL,--M: Masculino	F:Femenina
	TELEFONO varchar(20) NOT NULL,	
   DIRECCION varchar(70) NOT NULL,
	EMAIL varchar(50) NOT NULL,      
	ESTADO char(1) check(Estado IN('E','H')) NOT NULL,--E: Eventual		H:Habitual
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO

--Tabla persona
CREATE TABLE [dbo].[Persona](
	ID_PERSONA integer PRIMARY KEY IDENTITY(1,1),
   NOMBRE varchar(100) NOT NULL,
   APE_PATERNO varchar(100) NOT NULL,
	APE_MATERNO varchar(100) NOT NULL,
	DNI integer NOT NULL,
	FECHA_NAC date NOT NULL,
	GENERO bit NOT NULL,
	EMAIL varchar(50) NOT NULL,
   DIRECCION varchar(70) NOT NULL,
	DEPARTAMENTO varchar(50) NOT NULL,
	PROVINCIA varchar(70) NOT NULL,
	DISTRITO varchar(70) NOT NULL,
   TELEFONO varchar(20) NOT NULL,    
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO
--Tabla rol
CREATE TABLE [dbo].[Rol](
	ID_ROL integer PRIMARY KEY IDENTITY,
   DESCRIPCION varchar(30) NOT NULL,
   ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO
--Tabla usuario

CREATE TABLE [dbo].[Usuario](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERSONA] [int] NOT NULL,
	[Username] [nvarchar](20) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
--	[Email] [nvarchar](30) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[LastLoginDate] [datetime] NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE PROCEDURE [dbo].[Insert_User]
	@ID_PERSONA int,
	@Username NVARCHAR(20),
	@Password NVARCHAR(20)
--	@Email NVARCHAR(30)
AS
BEGIN
	SET NOCOUNT ON;
	IF EXISTS(SELECT ID_USUARIO FROM Usuario WHERE Username = @Username)
	BEGIN
		SELECT -1 -- Username exists.
	END
	ELSE IF EXISTS(SELECT ID_USUARIO FROM Usuario WHERE ID_PERSONA = @ID_PERSONA)
	BEGIN
		SELECT -2 -- Person exists.
	END
	ELSE
	BEGIN
		INSERT INTO [Usuario]
			   ([ID_PERSONA]
			   ,[Username]
			   ,[Password]
			--   ,[Email]
			   ,[CreatedDate])
		VALUES
			   (@ID_PERSONA
			   ,@Username
			   ,@Password
			--   ,@Email
			   ,GETDATE())
		
		SELECT SCOPE_IDENTITY() -- UserId			   
     END
END

GO



CREATE TABLE [dbo].[UserActivation](
	[ID_USUARIO] [int] NOT NULL,
	[ActivationCode] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_UserActivation] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE  PROCEDURE [dbo].[Validate_User]
	@Username NVARCHAR(20),
	@Password NVARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @UserId INT, @LastLoginDate DATETIME
	
	SELECT @UserId = ID_USUARIO, @LastLoginDate = LastLoginDate 
	FROM Usuario WHERE Username = @Username AND [Password] = @Password
	
	IF @UserId IS NOT NULL
	BEGIN
		IF NOT EXISTS(SELECT ID_USUARIO FROM UserActivation WHERE ID_USUARIO = @UserId)
		BEGIN
			UPDATE Usuario
			SET LastLoginDate =  GETDATE()
			WHERE ID_USUARIO = @UserId
			SELECT @UserId [UserId] -- User Valid
		END
		ELSE
		BEGIN
			SELECT -2 -- User not activated.
		END
	END
	ELSE
	BEGIN
		SELECT -1 -- User invalid.
	END
END
GO

INSERT INTO Persona
SELECT 'william','santamaria','zeña','16769687','21/04/1963','1','admin@ferrotumi.com','av. panamerica 475','LAMBAYEQUE','LAMBAYEQUE','ILLIMO','950047269','0', GETDATE(),NULL,NULL
UNION ALL
SELECT 'martin','arriola','arriola','17653687','18/06/1968','1','user@ferrotumi.com','av. belaunde 3475','LAMBAYEQUE','CHICLAYO','CHICLAYO','926958569','0', GETDATE(),NULL,NULL
go 

INSERT INTO Usuario
SELECT '1','admin', 'admin', GETDATE(), NULL
UNION ALL
SELECT '2','user', '12345', GETDATE(), NULL
GO
--INSERT INTO UserActivation
--SELECT 2, NEWID()



--Tabla modulo
CREATE TABLE [dbo].[Modulo](
	ID_MODULO integer PRIMARY KEY IDENTITY,
   DESCRIPCION varchar(100) NOT NULL,
	ICONO varchar(100) NOT NULL,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL
);
GO

--Tabla operacion
CREATE TABLE [dbo].[Operacion](
	ID_OPERACION integer PRIMARY KEY IDENTITY,
	FK_ID_MODULO integer NOT NULL,
   DESCRIPCION varchar(100) NOT NULL,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
	FOREIGN KEY (FK_ID_MODULO) REFERENCES Modulo (ID_MODULO)
);
GO
--Tabla rol_operacion
CREATE TABLE [dbo].[Rol_Operacion](
	ID_ROL_OPERACION integer PRIMARY KEY IDENTITY,
	FK_ID_ROL integer NOT NULL,
   FK_ID_OPERACION integer NOT NULL,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
	FOREIGN KEY (FK_ID_ROL) REFERENCES Rol (ID_ROL),
	FOREIGN KEY (FK_ID_OPERACION) REFERENCES Operacion (ID_OPERACION)
);
GO
--Tabla ingreso
CREATE TABLE [dbo].[Ingreso](
	ID_INGRESO integer PRIMARY KEY IDENTITY,
   FK_ID_PROVEEDOR integer NOT NULL,
   FK_ID_USUARIO integer NOT NULL,
   TIPO_COMPROBANTE varchar(20) NOT NULL,
   SERIE_COMPROBANTE varchar(7) NULL,
   NUM_COMPROBANTE varchar (10) NOT NULL,
   IMPUESTO decimal (4,2) NOT NULL,
   TOTAL_INGRESO decimal (11,2) NOT NULL,
   ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
   FOREIGN KEY (FK_ID_PROVEEDOR) REFERENCES Persona (ID_PERSONA),
   FOREIGN KEY (FK_ID_USUARIO) REFERENCES Usuario (ID_USUARIO)
);
GO
--Tabla detalle_ingreso
CREATE TABLE [dbo].[Detalle_Ingreso](
	ID_DETALLE_INGRESO integer PRIMARY KEY IDENTITY,
   FK_ID_INGRESO integer NOT NULL,
   FK_ID_PRODUCTO integer NOT NULL,
   CANTIDAD integer NOT NULL,
   PRECIO decimal(11,2) NOT NULL,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
   FOREIGN KEY (FK_ID_INGRESO) REFERENCES Ingreso (ID_INGRESO) ON DELETE CASCADE,
   FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES Producto (ID_PRODUCTO)
);
GO
--Tabla venta
CREATE TABLE [dbo].[Venta](
	ID_VENTA integer PRIMARY KEY IDENTITY,
   FK_ID_CLIENTE integer NOT NULL,
   FK_ID_USUARIO integer NOT NULL,
   TIPO_COMPROBANTE varchar(20) NOT NULL,
   SERIE_COMPROBANTE varchar(7) NULL,
   NUM_COMPROBANTE varchar (10) NOT NULL,
   IMPUESTO decimal (4,2) NOT NULL,
   TOTAL decimal (11,2)NOT NULL,
   ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
   FOREIGN KEY (FK_ID_CLIENTE) REFERENCES Persona (ID_PERSONA),
   FOREIGN KEY (FK_ID_USUARIO) REFERENCES Usuario (ID_USUARIO)
);
GO
--Tabla detalle_venta
CREATE TABLE [dbo].[Detalle_Venta](
	ID_DETALLE_VENTA integer PRIMARY KEY IDENTITY,
   FK_ID_VENTA integer NOT NULL,
   FK_ID_PRODUCTO integer NOT NULL,
   CANTIDAD integer NOT NULL,
   PRECIO decimal(11,2) NOT NULL,
   DESCUENTO decimal(11,2) NOT NULL,
	ELIM_LOGICO bit default(1),
	FECHA_INS datetime NULL,
	FECHA_UPD datetime NULL,
	FECHA_DEL datetime NULL,
   FOREIGN KEY (FK_ID_VENTA) REFERENCES Venta (ID_VENTA) ON DELETE CASCADE,
   FOREIGN KEY (FK_ID_PRODUCTO) REFERENCES Producto (ID_PRODUCTO)
);
GO

/*===============================PROCEDIMIENTOS ALMACENADOS==========================================*/
/*CLIENTE===================*/
--MOSTRAR
CREATE PROCEDURE [dbo].[sp_ClienteMostrar]
AS
   SELECT 
		CODIGO, 
		CONCAT(NOMBRE,' ',APE_PATERNO,' ',APE_MATERNO) AS CLIENTE,
		DNI,
		GENERO,
		TELEFONO,
		DIRECCION,
		EMAIL,
		ESTADO
	FROM [dbo].[Cliente]
	WHERE ELIM_LOGICO=1
GO

--INSERTAR 
CREATE PROCEDURE [dbo].[sp_ClienteInsertar]
	@NOMBRE varchar(100),	
   @APE_PATERNO varchar(100),
	@APE_MATERNO varchar(100),
	@DNI varchar(8),
	@GENERO char(1),
	@TELEFONO varchar(20),	
   @DIRECCION varchar(70),
	@EMAIL varchar(50),
	@ESTADO char(1)
AS
	INSERT INTO [dbo].[Cliente] (NOMBRE,
			APE_PATERNO,
			APE_MATERNO,
			DNI,
			GENERO,
			TELEFONO,
			DIRECCION,
			EMAIL,
			ESTADO,
			FECHA_INS)
		VALUES (@NOMBRE,
			@APE_PATERNO,
			@APE_MATERNO,
			@DNI,
			@GENERO,
			@TELEFONO,
			@DIRECCION,
			@EMAIL,
			@ESTADO,
			CURRENT_TIMESTAMP)
GO

--EDITAR
CREATE PROCEDURE [dbo].[sp_ClienteEditar]
	@NOMBRE varchar(100),
   @APE_PATERNO varchar(100),
	@APE_MATERNO varchar(100),
	@DNI varchar(8),
	@GENERO char(1),
	@TELEFONO varchar(20),	
   @DIRECCION varchar(70),
	@EMAIL varchar(50),
	@ESTADO char(1),
	@ID_CLIENTE integer
AS
	UPDATE [dbo].[Cliente]
		SET NOMBRE=@NOMBRE
			,APE_PATERNO=@APE_PATERNO
			,APE_MATERNO=@APE_MATERNO
			,DNI=@DNI
			,GENERO=@GENERO
			,TELEFONO=@TELEFONO
			,DIRECCION=@DIRECCION
			,EMAIL=@EMAIL
			,ESTADO=@ESTADO
			,FECHA_UPD=CURRENT_TIMESTAMP
	WHERE ELIM_LOGICO=1 AND ID_CLIENTE=@ID_CLIENTE
GO
--ELIMINAR
CREATE PROCEDURE [dbo].[sp_ClienteEliminar]
	@ID_CLIENTE int
AS
	UPDATE [dbo].[Cliente] 
		SET 
			ELIM_LOGICO=0,FECHA_DEL=CURRENT_TIMESTAMP 
		WHERE ID_CLIENTE=@ID_CLIENTE
GO

/*CATEGORIA===================*/
--MOSTRAR
CREATE PROCEDURE [dbo].[Mostrar_Categoria]
AS
	SELECT 
			ID_CATEGORIA AS ID, 
			DESCRIPCION, 
			ESTADO_CATEGORIA AS ESTADO 
		FROM [dbo].[Categoria]
		WHERE ELIM_LOGICO=1
GO
--INSERTAR 
CREATE PROCEDURE [dbo].[Insertar_Categoria]
	@DESCRIPCION varchar(50),
	@ESTADO_CATEGORIA bit =1
AS
	INSERT INTO [dbo].[Categoria] (DESCRIPCION,ESTADO_CATEGORIA)
		VALUES (@DESCRIPCION,@ESTADO_CATEGORIA)
GO
--EDITAR
CREATE PROCEDURE [dbo].[Editar_Categoria]
	@DESCRIPCION varchar(50),
	@ESTADO_CATEGORIA bit =1,
	@ID_CATEGORIA int
AS
	UPDATE [dbo].[Categoria]
		SET 
			DESCRIPCION=@DESCRIPCION
			,ESTADO_CATEGORIA=@ESTADO_CATEGORIA 
		WHERE ELIM_LOGICO=0 AND ID_CATEGORIA=@ID_CATEGORIA
GO
--ELIMINAR
CREATE PROCEDURE [dbo].[Eliminar_Categoria]
	@ID_CATEGORIA int
AS
	UPDATE [dbo].[Categoria] 
		SET ELIM_LOGICO=0
			,FECHA_DEL=CURRENT_TIMESTAMP
		WHERE ELIM_LOGICO=1 AND ID_CATEGORIA=@ID_CATEGORIA
GO
--BUSCAR
CREATE PROCEDURE [dbo].[Buscar_Categoria]
	@ID_CATEGORIA int
AS
	SELECT 
			ID_CATEGORIA AS ID, 
			DESCRIPCION, 
			ESTADO_CATEGORIA AS ESTADO 
		FROM [dbo].[Categoria]
		WHERE ELIM_LOGICO=1 AND ID_CATEGORIA=@ID_CATEGORIA
GO

/*MARCA===================*/
--MOSTRAR
CREATE PROCEDURE [dbo].[Mostrar_Marca]
AS
	SELECT 
			ID_MARCA AS ID, 
			DESCRIPCION AS MARCA, 
			ESTADO_MARCA AS ESTADO
		FROM [dbo].[Marca]
		WHERE ELIM_LOGICO=1
GO
--INSERTAR 
CREATE PROCEDURE [dbo].[Insertar_Marca]
	@DESCRIPCION varchar(50),
	@ESTADO_MARCA bit =1
AS
	INSERT INTO Marca (DESCRIPCION,ESTADO_MARCA) VALUES (@DESCRIPCION,@ESTADO_MARCA)
GO
--EDITAR
CREATE PROCEDURE [dbo].[Editar_Marca]
	@DESCRIPCION varchar(50),
	@ESTADO_MARCA bit =1,
	@ID_MARCA int
AS
	UPDATE [dbo].[Marca] 
		SET DESCRIPCION=@DESCRIPCION
			,ESTADO_MARCA=@ESTADO_MARCA
		WHERE ID_MARCA=@ID_MARCA
GO
--ELIMINAR
CREATE PROCEDURE [dbo].[Eliminar_Marca]
	@ID_MARCA int
AS
	UPDATE [dbo].[Marca]
		SET ELIM_LOGICO=0
			,FECHA_DEL=CURRENT_TIMESTAMP
		WHERE ID_MARCA=@ID_MARCA

GO
--BUSCAR
CREATE PROCEDURE [dbo].[Buscar_Marca]
	@ID_MARCA int
AS
	SELECT 
			ID_MARCA AS ID,
			DESCRIPCION AS MARCA,
			ESTADO_MARCA AS ESTADO
		FROM [dbo].[Marca]
	WHERE ELIM_LOGICO=1 AND ID_MARCA=@ID_MARCA
GO

/*PRODUCTO===================*/
CREATE PROCEDURE [dbo].[Mostrar_Producto]
AS
	SELECT 
			ID_PRODUCTO AS ID,
			FK_ID_CATEGORIA AS CATEGORÍA,
			FK_ID_MARCA AS MARCA,
			CODIGO,
			DESCRIPCION AS NOMBRE,
			PRECIO_UNIT AS PRECIO,
			Stock,
			ESTADO_PRODUCTO AS ESTADO
	FROM [dbo].[Producto]
	WHERE ELIM_LOGICO=1

GO
--INSERTAR 
CREATE PROCEDURE [dbo].[Insertar_Producto]
	@FK_ID_CATEGORIA int,
	@FK_ID_MARCA int,
	@CODIGO varchar(50),
	@DESCRIPCION varchar(100),
	@PRECIO_UNIT decimal(11,2),
	@STOCK integer =0,
	@ESTADO_PRODUCTO bit =1
AS 
	INSERT INTO [dbo].[Producto]
			(FK_ID_CATEGORIA,
			FK_ID_MARCA,
			CODIGO,
			DESCRIPCION,
			PRECIO_UNIT,
			STOCK,
			ESTADO_PRODUCTO)
		VALUES
			(@FK_ID_CATEGORIA,@FK_ID_MARCA,@CODIGO,@DESCRIPCION,@PRECIO_UNIT,@STOCK,@ESTADO_PRODUCTO)
GO
--EDITAR
CREATE PROCEDURE [dbo].[Editar_Producto]
	@FK_ID_CATEGORIA int,
	@FK_ID_MARCA int,
	@CODIGO varchar(50),
	@DESCRIPCION varchar(100),
	@PRECIO_UNIT decimal(11,2),
	@STOCK int,
	@ESTADO_PRODUCTO bit =1,
	@ID_PRODUCTO int
AS
	UPDATE [dbo].[Producto] 
		SET 
			FK_ID_CATEGORIA=@FK_ID_CATEGORIA
			,FK_ID_MARCA=@FK_ID_MARCA
			,CODIGO=@CODIGO
			,@DESCRIPCION=@DESCRIPCION
			,PRECIO_UNIT=@PRECIO_UNIT
			,STOCK=@STOCK
			,ESTADO_PRODUCTO=@ESTADO_PRODUCTO
	WHERE ID_PRODUCTO=@ID_PRODUCTO
GO
--ELIMINAR
CREATE PROCEDURE [dbo].[Eliminar_Producto]
	@ID_PRODUCTO int
As
	UPDATE [dbo].[Producto]
		SET ELIM_LOGICO=0
			,FECHA_DEL=CURRENT_TIMESTAMP
	WHERE ID_PRODUCTO=@ID_PRODUCTO
GO
--BUSCAR
CREATE PROCEDURE [dbo].[Buscar_Producto]
	@ID_PRODUCTO int
AS
SELECT 
		ID_PRODUCTO AS ID,
		FK_ID_CATEGORIA AS CATEGORÍA,
		FK_ID_MARCA AS MARCA,
		CODIGO AS CÓDIGO,
		DESCRIPCION AS NOMBRE,
		PRECIO_UNIT AS PRECIO,
		STOCK,
		ESTADO_PRODUCTO AS ESTADO
	FROM [dbo].[Producto]
	WHERE ELIM_LOGICO=1 AND ID_PRODUCTO=@ID_PRODUCTO
GO

/*PERSONA==================*/
CREATE PROCEDURE [dbo].[Mostrar_Persona]
AS
	SELECT 
			ID_PERSONA AS ID,
			CONCAT(NOMBRE,' ',APE_PATERNO,' ',APE_MATERNO) AS NOMBRE,
			DNI AS NÚMERO,
			DIRECCION AS DIRECCION,
			TELEFONO AS TELEFONO,
			EMAIL AS EMAIL
	FROM [dbo].[Persona]
	WHERE ELIM_LOGICO=1

GO
--INSERTAR 
CREATE PROCEDURE [dbo].[Insertar_Persona]
   @NOMBRE varchar(100),
   @APE_PATERNO varchar(100),
	@APE_MATERNO varchar(100),
	@DNI integer,
	@FECHA_NAC date,
	@GENERO bit,
	@EMAIL varchar(50),
   @DIRECCION varchar(70),
	@DEPARTAMENTO varchar(50),
	@PROVINCIA varchar(70),
	@DISTRITO varchar(70),
   @TELEFONO varchar(20)

AS
	INSERT INTO [dbo].Persona (
			NOMBRE,
			APE_PATERNO,
			APE_MATERNO,
			DNI,
			FECHA_NAC,
			GENERO,
			EMAIL,
			DIRECCION,
			DEPARTAMENTO,
			PROVINCIA,
			DISTRITO,
			TELEFONO
			) 
		VALUES (
			@NOMBRE,
			@APE_PATERNO,
			@APE_MATERNO,
			@DNI,
			@FECHA_NAC,
			@GENERO,
			@EMAIL,
			@DIRECCION,
			@DEPARTAMENTO,
			@PROVINCIA,
			@DISTRITO,
			@TELEFONO
)
GO
--EDITAR
CREATE PROCEDURE [dbo].[Editar_Persona]
	@NOM_PERSONA varchar(100),
	@APE_PATERNO_PERSONA varchar(100),
	@APE_MATERNO_PERSONA varchar(100),
	@DNI_PERSONA int,
	@FECHA_NAC_PERSONA date,
	@GENERO_PERSONA int,
	@EMAIL_PERSONA varchar(50),
	@DIRECCION_PERSONA varchar(70),
	@DEPARTAMENTO_PERSONA varchar(50),
	@PROVINCIA_PERSONA varchar(70),
	@DISTRITO_PERSONA varchar(70),
    @TELEFONO_PERSONA varchar(20),
	@ID_PERSONA int
AS
	UPDATE [dbo].[Persona] 
		SET 
			NOMBRE=@NOM_PERSONA,
			APE_PATERNO=@APE_PATERNO_PERSONA,
			APE_MATERNO=@APE_MATERNO_PERSONA,
			DNI=@DNI_PERSONA,
			FECHA_NAC=@FECHA_NAC_PERSONA,
			GENERO=@GENERO_PERSONA,
			EMAIL=@EMAIL_PERSONA,
			DIRECCION=@DIRECCION_PERSONA,
			DEPARTAMENTO=@DEPARTAMENTO_PERSONA,
			PROVINCIA=@PROVINCIA_PERSONA,
			DISTRITO=@DISTRITO_PERSONA,
			TELEFONO=@TELEFONO_PERSONA
	WHERE ID_PERSONA=@ID_PERSONA
GO

--ELIMINAR
CREATE PROCEDURE [dbo].[Eliminar_Persona]
	@ID_PERSONA int
AS
	UPDATE [dbo].[Persona]
		SET ELIM_LOGICO=0
			,FECHA_DEL=CURRENT_TIMESTAMP
	WHERE ID_PERSONA=@ID_PERSONA
GO
--BUSCAR
CREATE PROCEDURE [dbo].[Buscar_Persona]
	@ID_PERSONA int
AS
	SELECT 
			ID_PERSONA AS ID,
			NOMBRE,
			APE_PATERNO AS APELLIDO_PATERNO,
			APE_MATERNO AS APELLIDO_MATERNO,
			DNI,
			FECHA_NAC,
			GENERO,
			EMAIL,
			DIRECCION,
			DEPARTAMENTO,
			PROVINCIA,
			DISTRITO,
			TELEFONO
	FROM [dbo].[Persona]
	WHERE ELIM_LOGICO=1 AND ID_PERSONA=@ID_PERSONA
GO

/*ROL==================*/
CREATE PROCEDURE [dbo].[Mostrar_Rol]
AS
	SELECT ID_ROL AS ID,  DESCRIPCION AS DESCRIPCIÓN
		FROM [dbo].[Rol]
		WHERE ELIM_LOGICO=1
GO

--INSERTAR 
CREATE PROCEDURE [dbo].[Insertar_Rol]
	@DESCRIPCION_ROL varchar(30)
AS
	INSERT INTO [dbo].Rol(
			DESCRIPCION)
	VALUES (@DESCRIPCION_ROL)
GO

--EDITAR
CREATE PROCEDURE [dbo].[Editar_Rol]
	@DESCRIPCION_ROL varchar(100),
		@ID_ROL int
AS
	UPDATE [dbo].[Rol] 
		SET 
			DESCRIPCION=@DESCRIPCION_ROL
		WHERE ID_ROL=@ID_ROL
GO
--ELIMINAR
CREATE PROCEDURE [dbo].[Eliminar_Rol]
	@ID_ROL int
AS
	UPDATE [dbo].[Rol]
		SET ELIM_LOGICO=0
			,FECHA_DEL=CURRENT_TIMESTAMP
		WHERE ID_ROL=@ID_ROL
GO
--BUSCAR
CREATE PROCEDURE [dbo].[Buscar_Rol]
	@ID_ROL int
AS
	SELECT 
			ID_ROL AS ID,
			DESCRIPCION AS DESCRIPCIÓN
	FROM [dbo].[Rol]
		WHERE ELIM_LOGICO=1 AND ID_ROL=@ID_ROL
GO

/*USUARIO==================*/
CREATE PROCEDURE [dbo].[Mostrar_Usuario]
AS
	SELECT 
			[ID_PERSONA]
			,[Username]
			,[Password]
		--   ,[Email]
			,[CreatedDate]
	FROM Usuario
GO

--select * from usuario

